export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS= "LOGIN_SUCCESS"
export const LOGIN_FAIL= "LOGIN_FAIL"

export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL"

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL="LOAD_USER_FAIL"

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const LOGOUT_FAIL="LOGOUT_FAIL"

export const UPDATE_PROFILE_REQUEST= "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS= "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL= "UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET= "UPDATE_PROFILE_RESET"

export const UPDATE_PASSWORD_REQUEST= "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS= "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAIL= "UPDATE_PASSWORD_FAIL"
export const UPDATE_PASSWORD_RESET= "UPDATE_PASSWORD_RESET"

export const FORGOT_PASSWORD_REQUEST= "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS= "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL= "FORGOT_PASSWORD_FAIL"

export const NEW_PASSWORD_REQUEST= "NEW_PASSWORD_REQUEST"
export const NEW_PASSWORD_SUCCESS= "NEW_PASSWORD_SUCCESS"
export const NEW_PASSWORD_FAIL= "NEW_PASSWORD_FAIL"

export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST"
export const ADMIN_USERS_SUCCESS = "ADMIN_USERS_SUCCESS"
export const ADMIN_USERS_FAIL = "ADMIN_USERS_FAIL"

export const  ADMIN_DELETE_USER_REQUEST="ADMIN_DELETE_USER_REQUEST"
export const  ADMIN_DELETE_USER_SUCCESS="ADMIN_DELETE_USER_SUCCESS"
export const  ADMIN_DELETE_USER_FAIL="ADMIN_DELETE_USER_FAIL"

export const ADMIN_USER_DETAILS_REQUEST=" ADMIN_USER_DETAILS_REQUEST"
export const ADMIN_USER_DETAILS_SUCCESS="DMIN_USER_DETAILS_SUCCESS"
export const ADMIN_USER_DETAILS_FAIL="ADMIN_USER_DETAILS_FAI"

export const ADMIN_USER_UPDATE_REQUEST="ADMIN_USER_UPDATE_REQUEST"
export const ADMIN_USER_UPDATE_SUCCESS="DMIN_USER_UPDATE_SUCCESS"
export const ADMIN_USER_UPDATE_FAIL="ADMIN_USER_UPDATE_FAI"
export const ADMIN_USER_UPDATE_RESET="ADMIN_USER_UPDATE_RESET"


export const CLEAR_ERRORS="CLEAR_ERRORS"